### ISSUE TITLE
Datenpunkt Hc1HeatCurve wird nur aktualisiert wenn er per eBusd aktualisiert wird

### ISSUE THREAD

**Issue by SkeeveKlah** [rg-engineering/ioBroker.ebus#13]
Datenpunkte wie Wassdruck oder Vor- und Rücklauf aktualisieren sich von alleine, nur die Heizkurve nicht. Schreiben klappt problemlos per Adapter. Der geänderte Heiukurvenwert wird erst im Datenpunkt aktualisiert wenn ich ihn direkt mit "ebusctl read -f Hc1HeatCurve" am ebusd lese.
Das wäre ja der beschriebene Pull der auch per Adapter gehen soll, da kommt allerdings im Log eine Meldung das Hc1HeatCurve nicht gefunden werden kann "received ERR: element not found for Hc1HeatCurve". Es kommt übrigens auch eine Fehlermeldung wenn die Pull-LIste leer ist "received ERR: element not found for". Im HTTP ist der Wert für die Kurve drin:
`   "Hc1HeatCurve": {
    "name": "Hc1HeatCurve",
    "passive": false,
    "write": false,
    "lastup": 1573239481,
    "zz": 21,
    "fields": {
     "curve": {"value": 1.00}
    }
   },`

**Comment by rg-engineering** [comment]
@SkeeveKlah ist das noch aktuell? wenn nicht, schliesse ich das issue...

**Comment by SkeeveKlah** [comment]
Also eigentlich weigere ich mich vor Oktober die Heizung anzuwerfen, aber bei der aktuellen Wetterlage will ich mal nicht so sein ;-)
Mit der 2.2.7 läuft es. Kann geschlossen werden. Danke!
