### ISSUE TITLE
Getting error with adapter version 3.2.3

### ISSUE THREAD

**Issue by Fortune95** [rg-engineering/ioBroker.ebus#213]
js-controller: 5.0.16
Node.js: v18.18.2

Following error appears after the update to 3.2.3:

exception in ebusd_ReceiveData [Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/iobroker/node_modules/flat/index.js from /opt/iobroker/node_modules/iobroker.ebus/main.js not supported.Instead change the require of index.js in /opt/iobroker/node_modules/iobroker.ebus/main.js to a dynamic import() which is available in all CommonJS modules.]

**Comment by rg-engineering** [comment]
should be solved with 3.2.4

**Comment by Fortune95** [comment]
Yes it’s solved. Thank you!
