### ISSUE TITLE
unsupported ebusd version found (too new): 23.3 supported version is 23.2

### ISSUE THREAD

**Issue by downset** [rg-engineering/ioBroker.ebus#245]
Since updating my ebusd and my ebusadapter to the newest releases I am getting this Error

`ebus.0 | 2024-01-20 14:34:15.217 | info | unsupported ebusd version found (too new): 23.3 supported version is 23.2
-- | -- | -- | --
ebus.0 | 2024-01-20 14:34:15.216 | info | installed ebusd version is 23.3
ebus.0 | 2024-01-20 14:34:15.066 | warn | no update since 20.1.2024, 12:01:23 broadcast.messages.signoflife.lastup`

just would like to inform you about the new release and the resulting error, for the case you haven`t already notified the new ebusd release

**Comment by dhaumann** [comment]
@rg-engineering I'm also running into this issue. Would you possibly consider making a new release? Even though it's likely minor, it would still be appreciated a lot. Thanks for your time!

**Comment by rg-engineering** [comment]
![grafik](https://github.com/rg-engineering/ioBroker.ebus/assets/8238668/62b9c273-3ffd-46b5-b147-940e0075face)

only available in beta, net yet in stable...
