### ISSUE TITLE
V2.1.0 Fehler "object cmd not found"

### ISSUE THREAD

**Issue by MarkusEder** [rg-engineering/ioBroker.ebus#26]
Hi, 
Die "Version 1.0.0 in /opt/iobroker/node_modules/iobroker.ebus, node: v12.18.0, js-controller: 3.1.4" funktioniert ohne Fehler, nach dem Upgrade auf:
"Version 2.1.0 in /opt/iobroker/node_modules/iobroker.ebus, node: v12.18.0, js-controller: 3.1.4" kommt der Fehler "object cmd not found null"
zurück auf 1.0.0 ist der Fehler auch wieder weg.

Danke und Grüsse

**Comment by NemoN** [comment]
das gleiche hier auch... Werte werden aber scheinbar korrekt aktualisiert

**Comment by rg-engineering** [comment]
ist nur ein log ohne weitere Folgen...
siehe auch
https://forum.iobroker.net/topic/9844/adapter-ebus/236

**Comment by MarkusEder** [comment]
Stimmt, Werte werden korrekt aktualisiert auch mit der aktuellen ebusd 3.4.v3.4-20.
