### ISSUE TITLE
Compatibility EbusD Release 24.1

### ISSUE THREAD

**Issue by dirk99** [rg-engineering/ioBroker.ebus#380]
ebusd has been updated to release 24.1. Can you customize the adapter? 

LOG
unsupported ebusd version found (too new): 24.1 supported version is 23.3

Thanks

**Comment by rg-engineering** [comment]
@dirk99 hast du den ebusd 24.1 bei dir laufen? funktioniert das? Ich kann bei mir derzeit nicht testen...

**Comment by dirk99** [comment]
@rg-engineering ja, bei mir läuft er. Ich habe den Code nur für den Versionscheck angepasst, damit ich nicht immer die Meldung bekomme das 24.1 zu neu ist

**Comment by Fortune95** [comment]
@rg-engineering Bei mir läuft auch die 24.1.
Folgendes konnte ich feststellen:
- Datenpunkte wurden an anderer Stelle bzw. neue Struktur erstellt
- Versionswarnung
- Warnung bei jeden Scan vom Datenpunkt  “Scan.08.messages.Id.lastup”, dieser wurden nachdem Update angelegt wird aber nicht aktualisiert. Wenn ich ihn lösche, wird er aber wieder angelegt. Warum bekommt er nach einem Scan keinen neuen Zeitstempel?

**Comment by rg-engineering** [comment]
>Warnung bei jeden Scan vom Datenpunkt “Scan.08.messages.Id.lastup”, dieser wurden nachdem Update angelegt wird aber nicht aktualisiert. Wenn ich ihn lösche, wird er aber wieder angelegt. Warum bekommt er nach einem Scan keinen neuen Zeitstempel?

Das liegt normalerweise weder am Adapter noch am ebusd. Das Problem ist, dass manche Werte nach einem Reboot mit Scan einmalig auf dem Bus auftauchen. Der ebusd packt diese Werte in die Datenstruktur und damit tauchen sie im Adapter auf. Wenn nun dieser Wert nie wieder auf dem Bus auftaucht, bleibt natürlich der Zeitstempel beim ersten Auftauchen stehen und der Adapter loggt, dass es kein update gibt, was ja auch richtig ist.
Man wird diese Werte los, indem man den ebusd neu bootet. Dabei darf natürlich der Scan nicht aktiv sein. Dadurch baut der ebusd seine interne Datenstruktur neu auf. Danach löscht man im iobroker einmalig den kompletten Baum der Daten vom ebus-Adapter (oder alternativ manuell die Datenpunkte, die nicht aktualisiert werden)

**Comment by Fortune95** [comment]
Vielen Dank für Deine ausführliche Erklärung. Er legt zwar die Datenpunkte an, aber die Warnung kommt nicht mehr. Ich hätte gedacht, das der Adapter sie dann auch nicht mehr anlegt wenn sie beim Neubau der internen Datenstruktur fehlen.

**Comment by rg-engineering** [comment]
ja, ich sehe, ich muss doch Änderungen machen...
ebusd 24.1 legt Datenpunkte teilweise unter anderen Namen an:
* aus "scan" wurde "Scan"
* aus "broadcast" wurde "Broadcast"
* manche andere Datenpunkte sind bzgl. name und value in zwei Pfade aufgeteilt
