### ISSUE TITLE
Option to show binary states as boolean

### ISSUE THREAD

**Issue by Crazyachmed** [rg-engineering/ioBroker.ebus#40]
Binary states, for example a pump, are represented as a on/off string-object inside iobroker. This currently requires me to rewrite them to a virtual boolean object to save them (sensibly) in influx.

To not break existing installations there should be a general toggle to save these kinds of datapoints as boolean and not on/off string objects.

**Comment by rg-engineering** [comment]
should be solved with 2.3.2

**Comment by Crazyachmed** [comment]
Works just fine! :)
