### ISSUE TITLE
Invalid ID: ebus.0.ehp.messages.ActualEnvironmentPowerFine-u[SW>=414].lastup

### ISSUE THREAD

**Issue by stephanritscher** [rg-engineering/ioBroker.ebus#49]
**Describe the bug**  
With the latest ebusd, reading values from a Vaillant GeoTherm 81/3 fails each time due to an invalid ID.

**To Reproduce**  
1. Compile and install github master of ebusd.
2. Start iobroker with ebus cron enabled (no parameters configured for polling).
3. Each time the cron job runs, the following error appears in the iobroker protocol:
> exception in ebusd_ReceiveData [Error: Invalid ID: ebus.0.ehp.messages.ActualEnvironmentPowerFine-u[SW>=414].lastup]
4. Some of the states of ebus (e.g. ebus.0.hwc.messages.Status.fields.2.value=51,44) are not updated. This is also reflected by lastup states:
> ebus.0.cc.messages.Status.lastup = 13.7.2021 20:9:41
> ebus.0.hwc.messages.Status.lastup = 10.7.2021 22:59:46
5. ebusctl still works:
> $ ebusctl read -v -c hwc Status
> hwc Status temp0=80;onoff=off;temp=51.38;temp0=0

**Expected behavior**  
1. If one status could not be mapped correctly, others should not be affected (i.e. better error handling).
2. ebus names should be mapped to valid ioBroker IDs.

**Versions:**  
 - Adapter version: 2.2.7
 - JS-Controller version: 3.3.14
 - Node version: v14.17.0
 - Operating system: Fedora 34 ARM

**Additional context**  
The problem did not occur with an older ebusd version. Maybe the data field was added/renamed recently.

**Comment by stephanritscher** [comment]
According to
```const FORBIDDEN_CHARS = /[^._\-/ :!#$%&()+=@^{}|~\p{Ll}\p{Lu}\p{Nd}]+/gu;```
 also the greater sign (>) appearing in some fields is forbidden.
I have the following possibly problematic fields:
```
ActualEnvironmentPowerFine[SW>=414]
ActualEnvironmentPowerFine-u[SW>=414]
BadWeatherOMU2[airtobrinetowater][SW>=407]
BadWeatherOMU2-u[airtobrinetowater][SW>=407]
Bleeding[airtobrinetowater]
Bleeding-u[airtobrinetowater]
CondensorTemp[airtobrinetowater]
CondensorTemp-u[airtobrinetowater]
HotSummerOMU2[airtobrinetowater][SW>=407]
HotSummerOMU2-u[airtobrinetowater][SW>=407]
Source[airtobrinetowater]
SourcePumpStatus[SW>=407]
SourcePumpStatus-u[SW>=407]
SourceSwitch[airtobrinetowater]
SourceSwitch-u[airtobrinetowater]
SourceTempOutput[airtobrinetowater]
SourceTempOutput-u[airtobrinetowater]
Source-u[airtobrinetowater]
```

**Comment by rg-engineering** [comment]
can you please try the current version here from github? In my setup it works well. I'm only not sure about the case with two [ ][ ] like in your case...

**Comment by rg-engineering** [comment]
should be solved with 2.3.2

**Comment by stephanritscher** [comment]
Sorry for the late response.
I just installed the new version and it seems to solve the original problem.
However I get regular warnings:
- updateObject: not updated cc.messages.Status.fields.2.value value: null
- Key : cc.messages.Status.fields.2.value, Value : null name temp
I'm not sure about possible side effects, yet. I checked that these warnings didn't occur in the logs over the last few days (with the previous version and my workaround linked above), but now I see them every 5 minutes (each time ebus plugin is run by iobroker cron).
Any ideas?

**Comment by rg-engineering** [comment]
I know these logs and they were introduced with version 2.3.
The background for these logs is that there are apparently data points in the ebusd that have no (interpretable) value. I ignore these data points with the current version to avoid warnings from the js-controller.
