### ISSUE TITLE
Mehrfach-NTC-Sensor

### ISSUE THREAD

**Issue by andremueller83** [rg-engineering/ioBroker.ebus#56]
Hallo in die Runde,
habe ein kleines Problem. Ich habe ein Gesheizung mit Pufferspeicher, Solarkollektoren und Trinkwasseranlage.

Daten werden auch alle geladen.
`address 01: master #6
address 03: master #11
address 06: slave #6, scanned "MF=Vaillant;ID=PMS02;SW=0209;HW=8402", loaded "vaillant/06.pms.csv"
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0104;HW=7803", loaded "vaillant/bai.308523.inc", "vaillant/08.bai.csv"
address 0a: slave, scanned "MF=Vaillant;ID=PMW01;SW=0206;HW=8302", loaded "vaillant/0a.pmw.hwc.csv"
address 10: master #2
address 12: slave, scanned "MF=Vaillant;ID=PMW01;SW=0206;HW=8302"
address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0613;HW=6903", loaded "vaillant/15.700.csv"
address 26: slave, scanned "MF=Vaillant;ID=VR_71;SW=0104;HW=0503", loaded "vaillant/26.vr_71.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
address ec: slave, scanned "MF=Vaillant;ID=SOL00;SW=0613;HW=6903", loaded "vaillant/ec.sol.sc.csv"
address ed: slave, scanned "MF=Vaillant;ID=PMS02;SW=0209;HW=8402"
address f7: master #20
address fc: slave #20, scanned "MF=Vaillant;ID=PMW01;SW=0206;HW=8302"`

Jetzt zum Problem. Sowohl in der "vaillant/06.pms.csv"
`r,,Ntc1Sensor,NTC 1 Sensor,,,,"0500",,,tempsensor,,,Temperature in solar flow (from solar collector)
r,,Ntc2Sensor,NTC 2 Sensor,,,,"0600",,,tempsensor,,,Temperature in solar back flow (to solar collector)
r,,Ntc3Sensor,NTC 3 Sensor,,,,"0700",,,tempsensor,,,Temperature in buffer flow (to buffer)
r,,Ntc4Sensor,NTC 4 Sensor,,,,"0800",,,tempsensor,,,Temperature in buffer back flow (from buffer)`

als auch in der "0a.pmw.hwc.csv"
`r,,Ntc1Sensor,Ntc1Sensor,,,,"0000",,,tempsensor,,,T1 Temperature
r,,Ntc2Sensor,Ntc2Sensor,,,,"0100",,,tempsensor,,,T2 Temperature
r,,Ntc3Sensor,Ntc3Sensor,,,,"0200",,,tempsensor,,,T3 Temperature`

stehen NTC1Sensor, NTC2Sensor und NTC3Senor drin.

Aktuell kann der ebusd Adapter scheinbar nicht im ioBroker unterscheiden, welchen "Sensor 1" er einsammelt.

Aktuell sammelt er Sensor 1-3 nur vom "hwc" ein und nicht vom "pms". 

Anbei die Eintragungen, welche ich im ebusd Adapater im iobroker vorgenommen werden.
Ntc1Sensor,Ntc2Sensor,Ntc3Sensor,Ntc4Sensor,WaterPressure,SolarYieldTotal,MaintenanceDate,Hc1HeatCurve,ExternalHcRequest,ExternalHcTempDesired,ExternalHwcRequest,ExternalHwcTempDesired,ActualTappingTempDesired

**Comment by rg-engineering** [comment]
Mit Version 2.4. kann der circuit angegeben werden. Damit wird im read - Kommando auch der Parameter "-c circuit_name" mitgeschickt.
