### ISSUE TITLE
Adapter 2.4.5 don't know new ebusd Adapter 21.3

### ISSUE THREAD

**Issue by TeraX** [rg-engineering/ioBroker.ebus#63]
The current ebus Adapter 2.4.5 give a warning in iobroker logfile that the ebusd version 21.3 is too new.

<html>
<body>

ebus.0 | 2021-12-28 23:05:02.647 | info | unsupported ebusd version found (too new): 21.3 supported version is 21.2
-- | -- | -- | --
ebus.0 | 2021-12-28 23:05:02.647 | info | found ebusd version 21.3

</body>
</html>

**Comment by rg-engineering** [comment]
see https://github.com/rg-engineering/ioBroker.ebus/issues/62 -> already implemented in 2.5 and as beta available for installation...
