### ISSUE TITLE
3.0.2 How to enter additional polled datapoints

### ISSUE THREAD

**Issue by Beethoven56** [rg-engineering/ioBroker.ebus#74]
Hi y'all,
could you please explain how to enter additional polled datapoints
in Version 3.0.2 with syntax example.

**Comment by rg-engineering** [comment]
please explain in a bit more details what you really need...
just fill out the form like
![grafik](https://user-images.githubusercontent.com/8238668/174387640-59e4b85d-bbe9-47ef-8f1a-b7a3aea2ce1c.png)
