### ISSUE TITLE
Datenpunkt aktualisieren, wenn read-cmd verwendet wird

### ISSUE THREAD

**Issue by Standarduser** [rg-engineering/ioBroker.ebus#77]
Wenn außerhalb der zyklischen Abfrage ein Wert benötigt wird, kann dieser zum Beispiel über den Datenpunkt `ebus.0.cmd` aktiv abgefragt werden. Das Ergebnis ist im Datenpunkt `ebus.0.cmdResult` sichtbar.

Änderungswunsch:
Zusätzlich zu der Antwort in `ebus.0.cmdResult` sollte der Datenpunkt im Objektbaum aktualisiert werden, damit eine erleichterte Verarbeitung in der Visualisierung möglich ist.

Hintergrund:
Die Betriebsart der Warmwasserbereitung wurde per Script über den Befehl `write -c 700 HwcOpMode off` geändert. Die neue Betriebsart wird im Zweifel erst 5 Minuten später angezeigt, nachdem der Befehl abgesetzt wurde, da das generelle Abfrageintervall auf 5 Minuten gestellt ist.
Im Script möchte ich nach dem Senden des Write-Befehls den Befehl `read -f HwcOpMode` senden, um den Datenpunkt `ebus.0.700.messages.HwcOpMode.fields.opmode.value` direkt zu aktualisieren und so keinen inkonsistenten Anzeigezustand zu erzeugen. Bisher ist das nur über zusätzliche Datenpunkte möglich.

**Comment by cyberthom42** [comment]
Ich habe den gleichen Wunsch. Ich habe schon mehrere Workarounds versucht. Was wäre dafür aktuell der optimale Workaround?

**Comment by rg-engineering** [comment]
sollte mit der 3.1.0 erledigt sein

**Comment by rg-engineering** [comment]
@Standarduser gleiche Frage hier: issue schliessen?

**Comment by Standarduser** [comment]
Sorry, auch das ist bei mir untergegangen.
Kann es sein, dass du das ein wenig anders umgesetzt hast, als von mir erbeten?

Ich habe den Eindruck, dass geschriebene Werte direkt zurückgelesen werden - das gefällt mir sehr gut, danke!

Was auffällt ist jedoch folgendes:
- Ein Wert wird gelesen: `read -f ReturnTemp`
- Das Ergebnis erscheint recht schnell in `cmdResult`
- Mit größerer Verzögerung erscheint der Wert auch im eigentlichen Datenpunkt (bai.ReturnTemp)
- Zeitgleich werden auch jede Menge andere Datenpunkte aktualisiert, z.B. bai.FlowTemp oder 700.HwcOpMode

Ist dieses Verhalten Absicht?

**Comment by rg-engineering** [comment]
ja, das war ein Kompromiss zwischen Anforderung und Aufwand.
Nach dem Schreiben des Kommandos von ebus.0.cmd rufe ich einfach die komplette Datenabfrage auf, die auch zyklisch
gerufen wird. Damit aktualisieren sich alle Daten...
Einzelne Datenpunkte aktualisieren ist schwerig, da ich die Daten im Adapter nicht separat in Strukturen halte, sondern sie nur durchreiche. Ich müsste also eine Suche nach dem richtigen Datenpunkt einbauen. Das wollte ich mir ersparen...

**Comment by Standarduser** [comment]
Kann es dabei zu Konflikten kommen, wenn die zyklische Abfrage bereits läuft, oder aber nach Zeitplan gleich anfangen würde zu laufen?
Und wie verhält sich das, wenn ich zwei Werte nacheinander abfrage? Wird die gesamte Aktualisierung noch ein zweites Mal angestoßen oder wird die zweite verworfen oder die erste abgebrochen und die zweite gestartet?

**Comment by rg-engineering** [comment]
@Standarduser habe das noch etwas umgebaut um zu verhindern, dass mehrere Datenabfragen gleichzeitig stattfinden. Evtl. ist das ja sogar das Problem gewesen, als gar keine Daten mehr aktualisiert wurden...

**Comment by Standarduser** [comment]
So wie ich das aus dem Code lese, wird eine zweite Abfrage einfach verhindert.
Wäre es nicht besser, die erste zu stoppen und einen neuen zu starten?

Es ist ja nicht vorhersehbar, ob der zuletzt geschriebene Wert in der Lesereihenfolge nicht vielleicht vor dem ersten liegt und dieser somit erst beim nächsten zyklischen Abruf aktualisiert wird.

**Comment by rg-engineering** [comment]
nein, sie wird nicht verhindert, nur "gesammelt". Wenn nach dem ersten Kommando direkt ein zweites folgt, wird erstmal weiter gewartet. Erst wenn nach 500 ms kein weiteres Kommando kommt, werden alle Daten abgefragt. Falls zufälligerweise zur gleichen Zeit die zyklische Abfrage bereits aktiv sein sollte, wird nicht abgefragt, oder auch anders herum: falls die Abfrage aufgrund Kommando schon läuft, wird die zyklische Abfrage nicht ausgeführt...

**Comment by Standarduser** [comment]
Das mit dem Sammeln ist eine super Idee.
Wenn der Abstand zwischen zwei Kommandos jedoch größer ist, als 500ms, oder die zyklische Abfange noch läuft, jedoch schon fast durch ist, dann werden die Werte jedoch trotzdem nicht aktualisiert. Oder?

**Comment by cyberthom42** [comment]
Ich habe ein JavaScript Blockly Script geschrieben, welches zusätzlich zu den schon im ebus Adapter eingetragenen Abfragen alle 15 Sekunden über cmd read abfragen sendet (zum Teil die gleichen, nur eben nun mit 15 Sekunden statt den minimal möglichen 60 Sekunden). Diese werden um Objekt Result auch angezeigt, nur werden die Objekte im Objektbaum nicht aktuelisiert

**Comment by rg-engineering** [comment]
kannst du dazu ein debug log erzeugen? Wie oben geschrieben, sollte nach einem read-Kommando spätestens nach 500ms ein update erfolgen
