### ISSUE TITLE
Antwort in cmdResult "unsauber"

### ISSUE THREAD

**Issue by Standarduser** [rg-engineering/ioBroker.ebus#78]
Adapter-Version 3.0.2

Über den Datenpunkt `ebus.0.cmd` wird der Befehl `read -f HwcOpMode` gesendet.
Als Antwort liefert `ebus.0.cmdResult` den Wert `auto , `, wobei das hier dargestellte Leerzeichen zwischen dem eigentlichen Wert und dem Komma zwei Zeilenumbrüche sind.

Vollständige Antwort:
```
auto

, 
```

Erwartete Antwort:
```
auto
```

**Comment by rg-engineering** [comment]
sollte mit der 3.1.0 erledigt sein

**Comment by rg-engineering** [comment]
@Standarduser hattest du dir das schon mal angeschaut? Kann ich das issue schliessen?

**Comment by Standarduser** [comment]
Oh, tut mir leid für das fehlende Feedback.
Der konkret beschriebene Fall ist erledigt. Wenn ich den Wert wie oben beschrieben lese, lautet die Antwort jetzt `auto`.

Aber: bevor ich das soeben explizit getestet habe stand noch `auto , ` im Result. Möglicherweise war das jedoch ein Relikt, das kann ich leider nicht mehr nachvollziehen.
