### ISSUE TITLE
Update to ebusd Version 22.4

### ISSUE THREAD

**Issue by fredfesl** [rg-engineering/ioBroker.ebus#79]
Ich bekomme eine Info, dass die Version zu neu ist.
Kann man ein Update auf die ebusd Version 22.4 machen?

Der Adapter soll aber bis Version 22.3 unterstützen...

Vielen Dank!

![Info](https://user-images.githubusercontent.com/94286446/202250835-4b2b4b1f-cdaf-4c69-8e86-80432eff9e19.jpg)

**Comment by rg-engineering** [comment]
welche Version vom Adapter verwendest du? Die 3.0.7 unterstützt bis ebusd 22.3
Man kann sicher auch die 22.4 vom ebusd verwenden, das habe ich aber bisher noch nicht getestet...

**Comment by fredfesl** [comment]
Guten Abend,
Ich hatte die Version 3.0.2 Ich habe nun auf die Version 3.0.7 geupdatet.
![2022-11-17 18_52_40-instances - raspberrypi und 5 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/94286446/202520905-c34b7f33-3949-4278-b4b8-1261fee383c1.png)

Aber irgendwie habe ich immer noch einen Fehler.

![Log](https://user-images.githubusercontent.com/94286446/202519755-29396fd9-8dee-4036-a482-aff309eece77.png)

Wenn ich im Raspberry einen Wert lese mit  ebusctl read -c ehp ReturnTempMax funktioniert es:

![2022-11-17 18_48_39-pi@raspberrypi_ ~](https://user-images.githubusercontent.com/94286446/202520117-a0e4c822-b4f6-4c1f-aeb7-db133eab669a.png)

Was muss ich genau in cmd eingeben, um den Wert zu bekommen?
Nur read -c ehp ReturnTempMax . Das funktioniert irgendwie nicht...

![2022-11-17 18_50_16-objects - raspberrypi und 5 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/94286446/202520465-2a1d027a-ecc9-482d-a144-074ef192a246.png)

Die Objekte werden, aber minütlich aktualisiert:
![2022-11-17 18_51_50-objects - raspberrypi und 5 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/94286446/202520738-1d82e8f7-f473-4caa-9830-81be35493d78.png)

Vielen Dank!

**Comment by fredfesl** [comment]
Guten Abend,
aktuell funktioniert es. Ich hatte den falschen Telnet Port. Habe ihn im Iobroker auf 8888, so dass er identisch zu der Config von ebusd ist, geändert. Jetzt bekomme ich auch ein Ergebnis in cmdresult. 

![2022-11-17 18_52_40-instances - raspberrypi und 5 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/94286446/202561047-d738abfc-52b8-4f21-bc8d-94bbe365b9ab.png)

Danke für den Adapter!
