### ISSUE TITLE
Info Msg in Log "unsupported ebusd version" - There is a new ebus Version 23.1 available

### ISSUE THREAD

**Issue by TeraX** [rg-engineering/ioBroker.ebus#87]
Hi,

I get as warn level follow log message "unsupported ebusd version found (too new): 23.1 supported version is 22.3".

ebusd Version 23.1 is very new (available since 07-Jan-2023).

Thank you and best Regards

**Comment by rg-engineering** [comment]
can you confirm, that new ebusd version runs well with adapter? Otherwise I need to check by myself... 
Will update supported verion if it's clear that adapter and ebusd update are compatible...

**Comment by TeraX** [comment]
I will have a look for the next view days to check if there is everything working fine.

Best Regards
Daniel

**Comment by rg-engineering** [comment]
supported with 3.1.1
